### ISSUE TITLE
How to compile these?

### ISSUE THREAD

**Issue by jamiefolson** [ramnathv/slidifyExamples#2]
How does slidify find files?  Specifically, when I try to compile the revealjs

``` r
> getwd()
[1] ".../slidifyExamples/examples/revealjs"
> library(slidify)
> slidify("index.Rmd")

...
output file: /home/jfolson/git/slidifyExamples/examples/revealjs/index.md

Error in render(value, context) : could not find function "tmpl"
> 
```

Should I be doing this from somewhere else?

**Comment by ramnathv** [comment]
Apologies for the poor documentation on this. To run the examples in `slidifyExamples`, you need to have the `dev` versions of `slidify` and `slidifyLibraries`, which you can install from github by passing `ref = dev` to `intsall_github`. Second, in the `dev` version the main function is called `pagify`, since it can do more than just slides. I will set `slidify` as an alias to ensure backward compatibility, but I have not done that yet.

So, install dev versions and run `pagify` and it should work.

Let me know if you have trouble.

**Comment by jamiefolson** [comment]
So none of the `assets` or `libraries` in the root directory are required?

Are they already in the `slidifyLibraries` dev branch?

**Comment by ramnathv** [comment]
All library files are in the slidifyLibraries `dev` branch. Customizations in the `assets` folder are presentation specific and hence not in slidifyLibraries.

If you already have the libraries folder in the root directory, then you can set `url: {lib: path/to/libraries}` in the YAML front matter and slidify will automatically pick it up.

**Comment by jamiefolson** [comment]
It might be nice to be able to specify these during compilation in addition to in the actual file.

**Comment by ramnathv** [comment]
Can you elaborate more on what would you like to specify during compilation? The current design is to automatically include all css files found in `assets/css` and in addition you can specify the path to the assets folder using `{url: path/to/assets}` in the YAML front matter.

**Comment by jamiefolson** [comment]
Right.  I mean it'd be nice to be able to specify that url as an argument to `slidify`.  However, it might be better to specify it as the default, which I think you mentioned is possible.

**Comment by ramnathv** [comment]
There are two ways to specify the path to your assets folder.
1. In your YAML front matter, `url: {assets: path/to/assets}`.
2. Place a `config.yml` file in the root folder and add `url: {assets: path/to/assets}`

I have shied away from providing more arguments to the `slidify` function in the interest of reproducibility, but am willing to revisit this premise, if there is a promising use case.

**Comment by jamiefolson** [comment]
By "root folder" do you mean the directory from which `slidify` is run(ie `getwd()`) or the directory containing the `Rmd` file?

**Comment by ramnathv** [comment]
Currently, Slidify will look for `config.yml` in the directory containing the `Rmd` file. I plan to make it more flexible in the future. In the `dev` version (where `pagify` is the function to be used), you can run `pagify` from any directory. Slidify will switch to the required directory, run the required functions, and then return back to the directory you were working from.

**Comment by jamiefolson** [comment]
My concern is just that I don't want to duplicate a config.yaml for each end.

**Comment by jamiefolson** [comment]
I think I might just dynamically write the frontmatter using inherited properties.

**Comment by ramnathv** [comment]
If you are using the `author` function to initiate a slidedeck, in the next version, you will be able to provide a scaffolding template. This way you can package your `config.yml` and custom assets into a custom scaffold, which defaults to [this](https://github.com/ramnathv/slidify/tree/master/inst/skeleton).

If you have other suggestions which might make this simpler, let me know.
