### ISSUE TITLE
Problem with twocol layout

### ISSUE THREAD

**Issue by cpgonzal** [ramnathv/slidifyExamples#4]
Hi, ramnathv. I've recently installed the dev version of slidifyLibraries. I have a problem with twocol layout because I don't get the contents of the columns. I see the same problem in your example:

http://ramnathv.github.io/slidifyExamples/examples/landslide/#slide9

Do I write some different  to **\* left or **\* right before to each section? I have the following:

--- &twocol
### Two possibilities

**\* left
- something....

**\* right
- otherwise....

**Comment by ramnathv** [comment]
Use `=left` and `=right` in your Rmd file. I will update the documentation once I merge the dev branch with the master.

**Comment by cpgonzal** [comment]
Effectively, it works!. 
Thanks, ramnathv.
