### ISSUE TITLE
Is there some typo?

### ISSUE THREAD

**Issue by yanping** [ramnathv/slidifyExamples#5]
In [this file](https://github.com/ramnathv/slidifyExamples/blame/gh-pages/examples/revealjs/index.Rmd) 

Line 50: `<section>`

and

Line 60: `</section>`

**Comment by ramnathv** [comment]
Yes. I think I was experimenting with something and forgot to remove it before updating slidifyExamples.

**Comment by yanping** [comment]
Please remove them, thanks
